### ISSUE TITLE
Open Source Readiness for Slack Alert Service

### ISSUE THREAD

**Issue by Sachinbisht27** [DostEducation/slack-alert-service#1]
**Is your feature request related to a problem? Please describe.**
We wanted to make this repository an open-source repository for the Slack alert service.

**Describe the solution you'd like**
- [x] Add `README.md` with proper descriptions.
- [x] Add CI tools/GitHub workflows to the repository.
- [x] Add a good repository description.
- [x] Add LICENCE to the repository.
- [x] Add `pre-commit.yml` to the repository.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Acceptance Criteria**
- [x] The repository should be ready to use for any organization.
- [x] The repository should be a `public` repo.

**Documentation**
- [ ] Add Documentation as required

**Comment by Satendra-SR** [comment]
This is completed. Closing now
