### ISSUE TITLE
Documentation for the Slack Alert Service

### ISSUE THREAD

**Issue by Sachinbisht27** [DostEducation/slack-alert-service#2]
**Is your feature request related to a problem? Please describe.**
We wanted to make this repository an open-source repository for the Slack alert service. Hence we wanted to make the documentation for the whole product.

**Describe the solution you'd like**
- [x] Create a documentation for the service.
- [x] Add Steps to create a `slack-bot`.
- [x] Payload the slack bot is accepting.
- [x] Infrastructure requirement
- [x] Add the documentation to the issue comment and the Notion docs.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Acceptance Criteria**
- [x] The desired solution items should be fulfilled

**Documentation**
- [ ] Add Documentation as required

**Comment by Satendra-SR** [comment]
Notion document link for Slack alert service - https://www.notion.so/dosteducation/Slack-Alert-Service-bd476b5443e540c29430a56c18c5cce2
